
package com.itheima.customerService;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.itheima.crm.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.itheima.com/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByAddress", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByAddress")
    @ResponseWrapper(localName = "findByAddressResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByAddressResponse")
    public List<Customer> findByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.itheima.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephoneAndPassword", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByTelephoneAndPassword")
    @ResponseWrapper(localName = "findByTelephoneAndPasswordResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindByTelephoneAndPasswordResponse")
    public Customer findByTelephoneAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "changeFixedAreaIdById", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.ChangeFixedAreaIdById")
    @ResponseWrapper(localName = "changeFixedAreaIdByIdResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.ChangeFixedAreaIdByIdResponse")
    public void changeFixedAreaIdById(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SaveResponse")
    public void save(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.itheima.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setEmail", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SetEmail")
    @ResponseWrapper(localName = "setEmailResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SetEmailResponse")
    public void setEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setFixedAreaIdNull", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SetFixedAreaIdNull")
    @ResponseWrapper(localName = "setFixedAreaIdNullResponse", targetNamespace = "http://service.itheima.com/", className = "com.itheima.service.SetFixedAreaIdNullResponse")
    public void setFixedAreaIdNull(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Customer> arg0);

}
